### PR TITLE
ENH, WIP: Add support for binocular data

### LINKED ISSUE #4: Feature Request: Support Binocular data
This reader doesn't work with Binocular data, and adding this support might not be trivial:

From a quick glance I think the relevant parts of the code are below (and there may be more). Particularly, the `_to_list` call inside of `_handle_sample`

https://github.com/scott-huberty/eyelinkio/blob/dd8a313630eee62ad0d777f17ce5e997f21cffe8/eyelinkio/io/edf/read_edf.py#L437-L442

https://github.com/scott-huberty/eyelinkio/blob/dd8a313630eee62ad0d777f17ce5e997f21cffe8/eyelinkio/io/edf/read_edf.py#L310-L319

Our reader currently expects `idx` to be `0` (left eye) or `1` (right eye), and indexes `v` accordingly to grab the  [xpos ypos, _or_ pupil size] value for that sample. 

If we use xpos as an example, `v[0]` would be the xpos for the left eye, and `v[1]` would be the xpos for the right eye. For monocular data, only one of those indices will contain a non-null value, which is why we index it. However, For binocular data we assign `idx=2`, and `v[2]` will cause an index error (v has a length of 2.. one left eye value and one right-eye value...). In the case of binocular data we actually need to `v[:2]` to grab the xpos for both the eyes, since both indices have non-null values. 

The tricky part is that we are also going to have to adjust the shape of our samples array differently if our data are binocular:

Here:

https://github.com/scott-huberty/eyelinkio/blob/dd8a313630eee62ad0d777f17ce5e997f21cffe8/eyelinkio/io/edf/read_edf.py#L427-L434

I'm not working with Binocular data so probably won't get to this anytime soon.

### PR DESCRIPTION
**Pull request by scott-huberty**
Closes #4 . 

- [x] Refactor the `to_mne` method because for binocular data we don't need to append the eye to the channel names (they are derived from info["sample_fields"], which will already specify the eye in the case of binocular data).

- [x] Add a binocular test file

### CODE REVIEW

**Comment by ttngu207** [comment]
Hi @scott-huberty , I'm working with a project using EyeLink data, binocular and am searching for an open source python package to load the edf files.
What is the status of `binocular` development, is the `binocular` ready to use (at my own risk)?

**Comment by scott-huberty** [comment]
Hi @ttngu207,  I hadn't thought about this in a while but if this would be helpful to you I'd be happy to find some time for it!

To start, I think this PR is for the most part working. Can you check this branch out to confirm that it is able to load your binocular EDF files?

Other than that, I'm going to ping a colleague to request a tiny binocular EDF file (because I don't have one), but if I can't get one from them I might ask if you can share one.

**Comment by scott-huberty** [comment]
And to answer your question more directly, yes I think this branch is more or less good to use (at your own risk). But I can try to prioritize merging it to `main`.

**Comment by ttngu207** [comment]
Thanks @scott-huberty , that's good to hear. I can certainly be the one of the first guineapigs and will report back if it's ready to get merged into `main`

**Comment by scott-huberty** [comment]
@ttngu207 Were you able to test this branch with your data? Any luck?

**Comment by ttngu207** [comment]
> @ttngu207 Were you able to test this branch with your data? Any luck?

Hi, my apologies for the late follow up.
Yes I'm actually able to successfully load binocular EDF files - but needed to make a minor adjustment, see #7

**Comment by scott-huberty** [comment]
Alright merging to main. You should be good to use the main branch @ttngu207 . I committed some new code after your PR, If you run into new/other issues don't hesitate to open a ticket. thx!

**Pull request merged**
